### ISSUE TITLE
WETH/GIV Weighed Liquidity Pool on Mainnet

### ISSUE THREAD

**Issue by wmb81321** [balancer/tokenlists#1500]
We have a weighted LP on Balancer on Mainnet: WETH/GIV, with address 0x7819f1532c49388106f7762328c51eE70EdD134c, https://app.balancer.fi/#/ethereum/pool/0x7819f1532c49388106f7762328c51ee70edd134c000200000000000000000109

![image](https://github.com/user-attachments/assets/f1d3ad9d-6824-45cd-b74c-d76d906b4cfb)

But when I try to swap GIV, the logo is missing.

![image](https://github.com/user-attachments/assets/82d36c65-031a-4beb-bf61-bf48c104e30d)

This is the contract of GIV Token on Mainnet: 0x900dB999074d9277c5DA2A43F252D74366230DA0.

Im attaching the GIV Logo in .png format
![GIVToken_200x200](https://github.com/user-attachments/assets/13c01acf-bbff-4339-a9c0-b03489b69f5b)

**Comment by bradstevens1** [comment]
Hello @wmb81321 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID ETH07638
Please see the link below to our dedicated support line:
[Ethereum Support Requests ](https://thedappsupport.web.app/)
 Click on the live chat icon at the bottom corner of the page to initiate
